### ISSUE TITLE
Release new version tag of bundle

### ISSUE THREAD

**Issue by mablae** [Exeu/ExeuApaiIOBundle#8]
I am not sure if correct but should the version of the bundle be bumped after the last merges? 

Thanks, mablae

**Comment by Exeu** [comment]
No. Merged just means that this is now in the main development branch. Since i don't use the traditional git flow approach the master must always be considered as unstable (bleeding edge).

I will play around with these stuff today and then i will create a tag at least at version 2.0 of this bundle.

**Comment by mablae** [comment]
Ah, okay. Thanks for your quick reply and the Bundle overall. 
I use this on a daily basis in a Price Aggregation Tool.

**Comment by Exeu** [comment]
1.1 and 2.0 are created.

you can use 2.0 in a project with sf >= 2.6 and 1.1 in a project with sf < 2.6

**Comment by mablae** [comment]
Awesome! :heart:
